sudo: required
services:
 - docker

before_install:
 - sudo docker build -t ninja/docker-react -f Dockerfile.dev .


script:
 - sudo docker run -e CI=true ninja/docker-react npm run test 

deploy:
 edge: true
 provider: elasticbeanstalk
 region: "us-east-2"                                   
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-535466068727"                       
 bucket_path: "docker"
 on: 
  branch: master
 acess_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
